export const socialLinks = {
  github: "https://github.com/ZekaiShi",
  scholar: "https://scholar.google.com/citations?user=ThRaJWoAAAAJ&hl=en&oi=ao",
  email: "mailto:shizk2000@outlook.com",
};

export const profile = {
  en: {
    name: "ZEKAI SHI",
    role: "AI Researcher / Geo Vision",
    intro: "Ph.D. at XJTU",
    eyebrow: "RESEARCH IN PROGRESS",
    headlineStart: "Building Vision",
    headlineEnd: "for Our Planet",
    description:
      "Bridging computer vision and Earth observation. Exploring universal multimodal vision-language models to decode our planet.",
    tags: ["Multimodal Learning", "Earth Observation", "Computer Vision"],
    interests: "Research interests",
    research: "Research",
    publications: "Publications",
    news: "Latest Updates",
    researchBridge: "A RESEARCH THREAD",
    publicationsIntro:
      "Selected work in geospatial intelligence and visual learning.",
    skip: "Skip to content",
    home: "Back to top",
    navigation: "Main navigation",
    switchLanguage: "切换为中文",
    email: "Email Zekai Shi",
    contact: "Contact",
    explore: "Explore selected work",
    latest: "LATEST",
    paper: "Read paper",
    code: "Code",
    project: "Project",
    doi: "DOI / IEEE",
    scholarMore: "More on Google Scholar",
    footer: "Curiosity, computation, and a planet to understand.",
    display: "Display preferences",
    light: "Day",
    dark: "Night",
    system: "Auto",
    pause: "Pause animations",
    play: "Resume animations",
    reduced: "Reduced motion follows your system setting",
    terminalTitle: "researcher.config",
    terminalIntro: "Ph.D. at Xi’an Jiaotong University.",
    terminalMission: "Connect computer vision\nwith Earth observation.",
    terminalFocus:
      "Multimodal vision-language models\nfor understanding our planet.",
    terminalStatus: "Ideas welcome. Let’s connect.",
    terminalLabel: "Research profile terminal",
  },
  zh: {
    name: "师 泽楷",
    role: "AI 研究者 / 地理视觉",
    intro: "西安交通大学 博士",
    eyebrow: "探索进行中",
    headlineStart: "用视觉智能",
    headlineEnd: "解码地球",
    description:
      "连接计算机视觉与地球观测，探索通用多模态视觉语言模型，理解我们生活的星球。",
    tags: ["多模态学习", "地球观测", "计算机视觉"],
    interests: "研究兴趣",
    research: "研究方向",
    publications: "学术发表",
    news: "最新动态",
    researchBridge: "研究主线",
    publicationsIntro: "地理空间智能与视觉学习的部分研究成果。",
    skip: "跳转到正文",
    home: "返回顶部",
    navigation: "主导航",
    switchLanguage: "Switch to English",
    email: "发送邮件给师泽楷",
    contact: "联系",
    explore: "浏览研究成果",
    latest: "最新",
    paper: "阅读论文",
    code: "代码",
    project: "项目",
    doi: "DOI / IEEE",
    scholarMore: "在 Google Scholar 查看更多",
    footer: "以好奇心与计算，理解这颗星球。",
    display: "显示偏好",
    light: "白天",
    dark: "黑夜",
    system: "自动",
    pause: "暂停动效",
    play: "恢复动效",
    reduced: "已遵循系统的减少动态效果设置",
    terminalTitle: "researcher.config",
    terminalIntro: "西安交通大学 博士。",
    terminalMission: "连接计算机视觉\n与地球观测技术。",
    terminalFocus: "探索多模态视觉语言模型，\n理解我们的星球。",
    terminalStatus: "欢迎交流研究想法。",
    terminalLabel: "研究者简介终端",
  },
};

export const researchAreas = [
  {
    id: "alignment",
    code: "01",
    label: { en: "Multimodal", zh: "多模态" },
    title: {
      en: "Different signals. Shared meaning.",
      zh: "不同模态，共享语义。",
    },
    description: {
      en: "Exploring how visual, language, and geospatial representations meet.",
      zh: "探索视觉、语言与地理空间表征之间的联系。",
    },
    inputs: ["VISION", "LANGUAGE", "GEO"],
    output: "ALIGNMENT",
  },
  {
    id: "earth",
    code: "02",
    label: { en: "Earth observation", zh: "地球观测" },
    title: {
      en: "From satellite signals to insight.",
      zh: "从卫星信号，到地表认知。",
    },
    description: {
      en: "Learning from heterogeneous satellite data for surface pollutant retrieval.",
      zh: "从异构卫星数据中学习，研究地表污染物反演。",
    },
    inputs: ["SENSOR A", "SENSOR B", "SURFACE"],
    output: "RETRIEVAL",
  },
  {
    id: "vision",
    code: "03",
    label: { en: "Visual learning", zh: "视觉学习" },
    title: {
      en: "Learning to see the finer details.",
      zh: "学习看见，更精细的世界。",
    },
    description: {
      en: "Exploring representation learning and super-resolution for geospatial data.",
      zh: "探索地理空间数据的表征学习与超分辨率重建。",
    },
    inputs: ["PIXELS", "FEATURES", "CONTEXT"],
    output: "DETAIL",
  },
];
